language: nix
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ https://datakurre.cachix.org/" | sudo tee -a /etc/nix/nix.conf
- echo "require-sigs = false" | sudo tee -a /etc/nix/nix.conf
script: make $TARGET
env:
- PYTHON=python2 TARGET="nix-test nix-coverage"
- PYTHON=python3 TARGET="nix-test nix-coverage"
- PYTHON=python2 TARGET="docs"
after_success: make nix-coveralls
