name: "build"
on:
  push:
  pull_request:
jobs:
  smoketest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [python27, python39]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: datakurre
    - run: make nix-test nix-coverage nix-docs PYTHON=${{ matrix.python }}
